-- Supabase SQL for blog posts
create table if not exists articles (
  id text primary key,
  title text not null,
  category text not null default 'personal-finance',
  tags text[] not null default '{}',
  author text not null,
  "authorBio" text,
  "authorLink" text,
  date text not null,
  image text,
  summary text not null,
  body text not null,
  created_at timestamptz default timezone('utc'::text, now()) not null
);

alter table articles enable row level security;

create policy if not exists "Public read access for articles"
  on articles
  for select
  using (true);

create policy if not exists "Public insert access for articles"
  on articles
  for insert
  with check (true);

-- Existing comments table for the comment system
create table if not exists comments (
  id bigint generated by default as identity primary key,
  post_id text not null,
  name text not null,
  email text,
  comment text not null,
  date text not null,
  parent_id text,
  created_at timestamptz default timezone('utc'::text, now()) not null
);

alter table comments enable row level security;

create policy if not exists "Public read access for comments"
  on comments
  for select
  using (true);

create policy if not exists "Public insert access for comments"
  on comments
  for insert
  with check (true);
