/**
 * TRYUMPH MAGAZINE - DYNAMIC ENGINE & CMS API CONNECTOR
 */

// ==========================================================================
// SUPABASE CONFIGURATION HEADERS
// ==========================================================================
// Input your credentials below. If left empty, the comments system will 
// automatically fall back to local storage (safe for offline testing).
const SUPABASE_CONFIG = {
    url: "",      // Paste your Supabase Project URL here (e.g. https://xxxx.supabase.co)
    anonKey: ""  // Paste your Supabase Public Anon Key here
};

/* 
 * SQL schema to create the 'comments' table in your Supabase SQL Editor:
 *
 * create table comments (
 *   id bigint generated by default as identity primary key,
 *   post_id text not null,
 *   name text not null,
 *   comment text not null,
 *   date text not null,
 *   created_at timestamp with time zone default timezone('utc'::text, now()) not null
 * );
 * 
 * Make sure to enable Row Level Security (RLS) and create a policy 
 * allowing public insert and read access so users can comment.
 */

// Mobile Navigation Toggle
function toggleMenu() {
    const menu = document.querySelector('nav ul');
    const button = document.querySelector('.menu-toggle');
    if (menu && button) {
        menu.classList.toggle('active');
        button.classList.toggle('active');
    }
}

// Close Mobile Navigation
function closeMenu() {
    const menu = document.querySelector('nav ul');
    const button = document.querySelector('.menu-toggle');
    if (menu && button) {
        menu.classList.remove('active');
        button.classList.remove('active');
    }
}

// Toggle Dropdown on Mobile click
function toggleMobileDropdown(event) {
    if (window.innerWidth <= 768) {
        event.preventDefault();
        const parent = event.target.closest('.dropdown');
        if (parent) {
            parent.classList.toggle('open');
        }
    }
}

// ==========================================================================
// DARK/LIGHT THEME ENGINE (SVG ICONS - NO EMOJIS)
// ==========================================================================
const SUN_SVG = `<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="4"></circle><path d="M12 2v2"></path><path d="M12 20v2"></path><path d="M4.93 4.93l1.41 1.41"></path><path d="M17.66 17.66l1.41 1.41"></path><path d="M2 12h2"></path><path d="M20 12h2"></path><path d="M6.34 17.66l-1.41 1.41"></path><path d="M19.07 4.93l-1.41 1.41"></path></svg>`;
const MOON_SVG = `<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3a6 6 0 0 0 9 9 9 9 0 1 1-9-9Z"></path></svg>`;

function initTheme() {
    const savedTheme = localStorage.getItem('triumph_theme') || 'light';
    document.documentElement.setAttribute('data-theme', savedTheme);
    updateThemeIcon(savedTheme);
}

function toggleTheme() {
    const currentTheme = document.documentElement.getAttribute('data-theme') || 'light';
    const newTheme = currentTheme === 'light' ? 'dark' : 'light';
    document.documentElement.setAttribute('data-theme', newTheme);
    localStorage.setItem('triumph_theme', newTheme);
    updateThemeIcon(newTheme);
}

function updateThemeIcon(theme) {
    const themeBtn = document.getElementById('theme-toggle-btn');
    if (themeBtn) {
        if (theme === 'dark') {
            themeBtn.innerHTML = SUN_SVG;
            themeBtn.setAttribute('title', 'Switch to Light Mode');
        } else {
            themeBtn.innerHTML = MOON_SVG;
            themeBtn.setAttribute('title', 'Switch to Dark Mode');
        }
    }
}

// ==========================================================================
// CMS DATA LAYER (Tryumph Branding with posts.json fetch)
// ==========================================================================
const CMS_API = {
    // Local starter fallback articles if network fetch fails
    defaultArticles: [
        {
            id: "1",
            title: "How to make money online as a beginner: The Complete 2026 Guide",
            category: "personal-finance",
            tags: ["Personal Finance", "#SideHustle"],
            author: "Zikcolle",
            authorBio: "Financial analyst, trader, and founder of Tryumph's digital newsletter program.",
            authorLink: "about.html",
            date: "June 22, 2026",
            image: "simage/postiman.jpeg",
            summary: "In this post you will learn how to make money as a beginner as we delve into 20 ways you can earn using your phone and the internet.",
            body: "<p>In this post you will learn how to make money as a beginner as we delve into 20 proven methods to earn online. Millions of people leverage the digital space every single day to replace their full-time jobs, build passive side incomes, or launch high-growth careers. The methods below are verified, secure, and ideal for starting today.</p><h2>1. Leveraging Digital Agency Models</h2><p>The first model is similar to the traditional agency path. This requires gathering as much high-quality digital experience as possible (e.g., SEO, copy editing, copywriting, lead generation) and pitching these services directly to local businesses who need to optimize their web Presence. Since you act as an intermediary, you gain massive leverage with low capital constraints.</p><blockquote>\"Success in digital finance comes down to operational leverage and keeping customer acquisition costs low.\"</blockquote><p>By finding high-paying clients and outsourcing the workload to freelancers, you can scale the business indefinitely.</p>"
        }
    ],

    // Try fetching posts.json, fall back to localStorage if offline/local file
    async getArticles() {
        try {
            const response = await fetch('posts.json');
            if (response.ok) {
                // If it is in Decap CMS wrapper schema, parse array correctly
                const data = await response.json();
                return data.articles ? data.articles : data;
            }
        } catch (e) {
            console.log("Offline or local filesystem path. Loading local database copy.");
        }

        // Local Storage fallback
        if (!localStorage.getItem('triumph_articles')) {
            localStorage.setItem('triumph_articles', JSON.stringify(this.defaultArticles));
        }
        return JSON.parse(localStorage.getItem('triumph_articles'));
    },

    async getArticleById(id) {
        const articles = await this.getArticles();
        return articles.find(article => article.id === id);
    },

    async publishArticle(article) {
        const articles = await this.getArticles();
        articles.unshift(article);
        localStorage.setItem('triumph_articles', JSON.stringify(articles));
        return true;
    }
};

// ==========================================================================
// SUPABASE / LOCALSTORAGE HYBRID COMMENT ENGINE
// ==========================================================================
const COMMENTS_API = {
    async getComments(postId) {
        if (SUPABASE_CONFIG.url && SUPABASE_CONFIG.anonKey) {
            try {
                const url = `${SUPABASE_CONFIG.url}/rest/v1/comments?post_id=eq.${encodeURIComponent(postId)}&select=*`;
                const response = await fetch(url, {
                    method: 'GET',
                    headers: {
                        'apikey': SUPABASE_CONFIG.anonKey,
                        'Authorization': `Bearer ${SUPABASE_CONFIG.anonKey}`
                    }
                });
                if (response.ok) {
                    return await response.json();
                }
            } catch (e) {
                console.error("Failed to connect to Supabase database. Falling back to local storage comments.", e);
            }
        }

        // LocalStorage Fallback
        return JSON.parse(localStorage.getItem(`comments_${postId}`)) || [];
    },

    async addComment(postId, comment) {
        if (SUPABASE_CONFIG.url && SUPABASE_CONFIG.anonKey) {
            try {
                const url = `${SUPABASE_CONFIG.url}/rest/v1/comments`;
                const response = await fetch(url, {
                    method: 'POST',
                    headers: {
                        'apikey': SUPABASE_CONFIG.anonKey,
                        'Authorization': `Bearer ${SUPABASE_CONFIG.anonKey}`,
                        'Content-Type': 'application/json',
                        'Prefer': 'return=representation'
                    },
                    body: JSON.stringify({
                        post_id: postId,
                        name: comment.name,
                        comment: comment.comment,
                        date: comment.date
                    })
                });
                if (response.ok) {
                    return await this.getComments(postId);
                }
            } catch (e) {
                console.error("Failed to insert comment to Supabase database. Falling back to local storage comments.", e);
            }
        }

        // LocalStorage Fallback
        const comments = JSON.parse(localStorage.getItem(`comments_${postId}`)) || [];
        comments.push(comment);
        localStorage.setItem(`comments_${postId}`, JSON.stringify(comments));
        return comments;
    }
};

// ==========================================================================
// UTILITY ENGINE
// ==========================================================================
function calculateReadingTime(text) {
    const wordsPerMinute = 200;
    const words = text ? text.replace(/<[^>]*>/g, '').split(/\s+/).length : 0;
    return Math.max(1, Math.ceil(words / wordsPerMinute));
}

// ==========================================================================
// DYNAMIC DOM LOADERS & CONTROLLERS
// ==========================================================================
let activeCategory = 'all';
let currentArticlesList = [];

document.addEventListener('DOMContentLoaded', async () => {
    CMS_API.init ? CMS_API.init() : null;
    initTheme();

    const path = window.location.pathname;
    const isHome = path.includes('index.html') || path.endsWith('/');
    const isBlog = path.includes('blog.html');
    const isPost = path.includes('post.html');
    const isCMS = path.includes('cms.html');
    const isPress = path.includes('submit-press.html');

    const themeBtn = document.getElementById('theme-toggle-btn');
    if (themeBtn) {
        themeBtn.addEventListener('click', toggleTheme);
    }

    const params = new URLSearchParams(window.location.search);
    const categoryParam = params.get('cat');
    if (categoryParam) {
        activeCategory = categoryParam;
    }

    initBackToTop();

    if (isHome) {
        loadHomePage();
    } else if (isBlog) {
        loadBlogPage();
    } else if (isPost) {
        loadPostPage();
    } else if (isCMS) {
        loadCMSPage();
    } else if (isPress) {
        loadPressSubmissionPage();
    }
});

function initBackToTop() {
    const btn = document.getElementById('back-to-top-btn');
    if (!btn) return;

    window.addEventListener('scroll', () => {
        if (window.scrollY > 300) {
            btn.classList.add('visible');
        } else {
            btn.classList.remove('visible');
        }
    });

    btn.addEventListener('click', () => {
        window.scrollTo({
            top: 0,
            behavior: 'smooth'
        });
    });
}

function filterCategory(category) {
    activeCategory = category;
    renderFilteredArticles();
}

function runSearch(query) {
    const normalizedQuery = query.toLowerCase().trim();
    const cards = document.querySelectorAll('.blog-post, .feat-post');
    
    cards.forEach(card => {
        const title = card.querySelector('h2').innerText.toLowerCase();
        const summary = card.querySelector('p').innerText.toLowerCase();
        const category = card.getAttribute('data-category');

        const matchesSearch = title.includes(normalizedQuery) || summary.includes(normalizedQuery);
        const matchesCategory = (activeCategory === 'all' || category === activeCategory);

        if (matchesSearch && matchesCategory) {
            card.style.display = '';
        } else {
            card.style.display = 'none';
        }
    });
}

function renderFilteredArticles() {
    const postGrid = document.querySelector('.post-grid');
    if (!postGrid) return;

    postGrid.innerHTML = '';
    
    const displayList = activeCategory === 'all' 
        ? currentArticlesList 
        : currentArticlesList.filter(a => a.category === activeCategory);

    if (displayList.length === 0) {
        postGrid.innerHTML = `<div style="grid-column: 1/-1; text-align: center; color: var(--color-text-muted); padding: 40px;">No articles found in this category.</div>`;
        return;
    }

    displayList.forEach(article => {
        const readTime = calculateReadingTime(article.body || article.summary);
        const tagHTML = article.tags.map(t => `<span class="tag-pill">${t}</span>`).join('');
        
        const cardHTML = `
            <div class="blog-post" data-category="${article.category}">
                <div class="blog-post-image-wrapper">
                    <img src="${article.image || 'simage/postiman.jpeg'}" alt="${article.title}">
                </div>
                <div class="post-meta">
                    <span class="meta-author">By ${article.author}</span>
                    <span class="meta-divider">&bull;</span>
                    <span class="meta-date">${article.date}</span>
                    <span class="meta-divider">&bull;</span>
                    <span class="meta-time">${readTime} min read</span>
                </div>
                <h2><a href="post.html?id=${article.id}">${article.title}</a></h2>
                <p>${article.summary}</p>
                <div class="post-tags-container">
                    <span class="tags-label">Tags:</span>
                    ${tagHTML}
                </div>
                <a href="post.html?id=${article.id}" class="read-more">Read More</a>
            </div>
        `;
        postGrid.insertAdjacentHTML('beforeend', cardHTML);
    });
}

async function loadHomePage() {
    const allArticles = await CMS_API.getArticles();
    currentArticlesList = [...allArticles];
    
    const featured = currentArticlesList[0];
    const featPostContainer = document.querySelector('.feat-post');
    
    if (featured && featPostContainer) {
        const readTime = calculateReadingTime(featured.body || featured.summary);
        const tags = featured.tags.map(t => `<span class="tag-pill">${t}</span>`).join('');
        
        featPostContainer.setAttribute('data-category', featured.category);
        featPostContainer.innerHTML = `
            <div class="feat-post-image-wrapper">
                <img src="${featured.image || 'simage/postiman.jpeg'}" alt="${featured.title}">
            </div>
            <div class="feat-content">
                <div class="post-meta">
                    <span class="meta-author">By ${featured.author}</span>
                    <span class="meta-divider">&bull;</span>
                    <span class="meta-date">${featured.date}</span>
                    <span class="meta-divider">&bull;</span>
                    <span class="meta-time">${readTime} min read</span>
                </div>
                <h2><a href="post.html?id=${featured.id}">${featured.title}</a></h2>
                <p>${featured.summary}</p>
                <div class="post-tags-container">
                    <span class="tags-label">Tags:</span>
                    ${tags}
                </div>
                <a href="post.html?id=${featured.id}" class="read-more">Read More</a>
            </div>
        `;
    }

    const recentGridList = currentArticlesList.slice(1);
    currentArticlesList = recentGridList;
    renderFilteredArticles();

    renderExploreByCategory(allArticles);

    const homeSearch = document.getElementById('home-search-input');
    if (homeSearch) {
        homeSearch.addEventListener('input', (e) => {
            runSearch(e.target.value);
        });
    }
}

function renderExploreByCategory(articles) {
    const exploreGrid = document.getElementById('explore-category-grid');
    if (!exploreGrid) return;

    exploreGrid.innerHTML = '';
    const categories = [
        { key: 'investing', name: 'Investing' },
        { key: 'markets', name: 'Markets' },
        { key: 'crypto', name: 'Cryptocurrency' },
        { key: 'personal-finance', name: 'Personal Finance' }
    ];

    categories.forEach(cat => {
        const matchingPosts = articles.filter(a => a.category === cat.key);
        let listHTML = '';

        if (matchingPosts.length === 0) {
            listHTML = `<li style="color: var(--color-text-muted); font-size: 0.88rem; list-style: none;">No posts in this category yet.</li>`;
        } else {
            matchingPosts.forEach(post => {
                listHTML += `
                    <li>
                        <a href="post.html?id=${post.id}">${post.title}</a>
                        <span style="font-size: 0.75rem; color: var(--color-text-muted); display: block; margin-top: 2px;">${post.date}</span>
                    </li>
                `;
            });
        }

        const colHTML = `
            <div class="category-group-col">
                <h3>${cat.name}</h3>
                <ul>
                    ${listHTML}
                </ul>
            </div>
        `;
        exploreGrid.insertAdjacentHTML('beforeend', colHTML);
    });
}

async function loadBlogPage() {
    currentArticlesList = await CMS_API.getArticles();
    renderFilteredArticles();

    const blogSearch = document.getElementById('blog-search-input');
    if (blogSearch) {
        blogSearch.addEventListener('input', (e) => {
            runSearch(e.target.value);
        });
    }
}

async function loadPostPage() {
    const params = new URLSearchParams(window.location.search);
    const postId = params.get('id') || "1";
    
    const article = await CMS_API.getArticleById(postId);
    if (!article) {
        document.querySelector('main').innerHTML = `
            <div style="text-align: center; padding: 80px 0;">
                <h2>Article Not Found</h2>
                <p>The post you are searching for does not exist or has been deleted.</p>
                <a href="index.html" class="view-more">Back to Home</a>
            </div>
        `;
        return;
    }

    const computedReadTime = calculateReadingTime(article.body);

    document.title = `${article.title} | Tryumph Magazine`;
    
    const currentBreadcrumb = document.querySelector('.breadcrumbs li:last-child');
    if (currentBreadcrumb) {
        currentBreadcrumb.textContent = article.title;
    }
    const categoryBreadcrumb = document.querySelector('.breadcrumbs li:nth-child(2) a');
    if (categoryBreadcrumb) {
        categoryBreadcrumb.textContent = article.category.toUpperCase().replace('-', ' ');
        categoryBreadcrumb.href = `blog.html?cat=${article.category}`;
    }

    const postHeader = document.querySelector('.post-header');
    if (postHeader) {
        postHeader.querySelector('h1').textContent = article.title;
        
        const tagsWrapper = postHeader.querySelector('.post-tags-container');
        if (tagsWrapper) {
            tagsWrapper.innerHTML = `
                <span class="tags-label">Tags:</span>
                ${article.tags.map(t => `<span class="tag-pill">${t}</span>`).join('')}
            `;
        }

        const heroImage = postHeader.querySelector('.post-hero-image');
        if (heroImage) {
            heroImage.src = article.image;
            heroImage.alt = article.title;
        }

        const metaSpan = postHeader.querySelector('.post-meta');
        if (metaSpan) {
            metaSpan.innerHTML = `
                <span class="meta-author">By ${article.author}</span>
                <span class="meta-divider">&bull;</span>
                <span class="meta-date">${article.date}</span>
                <span class="meta-divider">&bull;</span>
                <span class="meta-time">${computedReadTime} min read</span>
            `;
        }
    }

    const contentBody = document.querySelector('.post-content');
    if (contentBody) {
        contentBody.innerHTML = article.body;
    }

    const bioWidget = document.getElementById('author-bio-widget');
    if (bioWidget) {
        bioWidget.innerHTML = `
            <h3>Author Profile</h3>
            <div class="author-bio-card" style="margin-top: 15px;">
                <h4 style="margin: 0; color: var(--color-primary); font-size: 1.15rem;">${article.author}</h4>
                <p style="font-size: 0.9rem; color: var(--color-text-muted); margin: 8px 0 12px 0; line-height: 1.45;">${article.authorBio}</p>
                <a href="${article.authorLink}" style="font-weight: 700; font-size: 0.85rem; text-transform: uppercase;">View Author Page &rarr;</a>
            </div>
        `;
    }

    loadCommentsSection(postId);
}

async function loadCommentsSection(postId) {
    const commentsList = document.getElementById('comments-list');
    const commentsCount = document.getElementById('comments-count');
    const commentForm = document.getElementById('comment-form');

    if (!commentsList) return;

    const renderComments = async () => {
        const comments = await COMMENTS_API.getComments(postId);
        commentsCount.textContent = `${comments.length} comment${comments.length !== 1 ? 's' : ''}`;
        
        commentsList.innerHTML = '';
        if (comments.length === 0) {
            commentsList.innerHTML = `<p style="color: var(--color-text-muted); font-style: italic;">No comments yet. Be the first to share your thoughts!</p>`;
            return;
        }

        comments.forEach(c => {
            const commentHTML = `
                <div class="comment-item" style="border-bottom: 1px solid var(--color-border); padding: 15px 0;">
                    <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 6px;">
                        <span style="font-weight: 700; color: var(--color-secondary);">${c.name}</span>
                        <span style="font-size: 0.75rem; color: var(--color-text-muted);">${c.date}</span>
                    </div>
                    <p style="margin: 0; font-size: 0.95rem; line-height: 1.5; color: var(--color-text-main);">${c.comment}</p>
                </div>
            `;
            commentsList.insertAdjacentHTML('beforeend', commentHTML);
        });
    };

    await renderComments();

    if (commentForm) {
        commentForm.onsubmit = async (e) => {
            e.preventDefault();
            const nameInput = document.getElementById('comment-name');
            const bodyInput = document.getElementById('comment-body');

            if (nameInput && bodyInput) {
                const now = new Date();
                const dateString = now.toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' });
                
                await COMMENTS_API.addComment(postId, {
                    name: nameInput.value,
                    comment: bodyInput.value,
                    date: dateString
                });

                bodyInput.value = '';
                nameInput.value = '';
                await renderComments();
            }
        };
    }
}

function loadCMSPage() {
    const cmsForm = document.getElementById('cms-publish-form');
    if (!cmsForm) return;

    cmsForm.onsubmit = async (e) => {
        e.preventDefault();

        const title = document.getElementById('cms-title').value;
        const category = document.getElementById('cms-category').value;
        const tagsString = document.getElementById('cms-tags').value;
        const author = document.getElementById('cms-author').value;
        const authorBio = document.getElementById('cms-author-bio').value;
        const summary = document.getElementById('cms-summary').value;
        const body = document.getElementById('cms-body').value;

        const tagsArray = tagsString.split(',').map(tag => tag.trim());
        const dateString = new Date().toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' });
        const id = 'post_' + Date.now();

        const newArticle = {
            id,
            title,
            category,
            tags: tagsArray,
            author,
            authorBio,
            authorLink: "about.html",
            date: dateString,
            image: "simage/postiman.jpeg",
            summary,
            body
        };

        await CMS_API.publishArticle(newArticle);
        alert('Article published successfully! Redirecting to Blog page...');
        window.location.href = 'blog.html';
    };
}

function loadPressSubmissionPage() {
    const pressForm = document.getElementById('press-submit-form');
    if (pressForm) {
        pressForm.onsubmit = (e) => {
            e.preventDefault();
            alert('Press Release pitched successfully! Our editorial desk will review it within 24 hours.');
            pressForm.reset();
        };
    }
}